### ISSUE TITLE
Landmarks

### ISSUE THREAD

**Issue by Zumbalamambo** [xiangrufan/keras-mtcnn#1]
How do I get landmarks as in [this](https://camo.githubusercontent.com/208be02edd9ecf8cfc02c7bf00f2d879c662f84e/68747470733a2f2f6b707a68616e6739332e6769746875622e696f2f4d54434e4e5f666163655f646574656374696f6e5f616c69676e6d656e742f70617065722f6578616d706c65732e706e67)

**Comment by xiangrufan** [comment]
The landmark is commented out in previous version of code. 
I just fixed this problem and you should be able to see the landmark in this version.

**Comment by Zumbalamambo** [comment]
Thank you so much. May i know why is that it is slow in realtime? is there any ways to speed it up in cpu?

**Comment by xiangrufan** [comment]
This conv-net is very sensitive to resolution of input image, reducing resolution may be a good way to speed it up. 
The first layer process the input image at full resolution, which is very slow when the image size is large.  it also gives much more positive detections to the second layer of mtcnn when resolution is large hence significantly slowed the detection process.

**Comment by Zumbalamambo** [comment]
May I know how do  I train the model with reduced resolution?

**Comment by xiangrufan** [comment]
you do not need to retrain a new model. just use input video or image of lower resolution.
